version: '3'
silent: true

dotenv: ['.env']

tasks:
  b:
    cmds:
      - go build ./...

  t:
    cmds:
      - go test ./...

  tc:
    cmds:
      - go test ./collections

  ti:
    cmds:
      - go test ./i18n

  tn:
    cmds:
      - go test ./xfs/nav

  tu:
    cmds:
      - go test ./xfs/utils

  dry:
    cmds:
      - ginkgo -v --dry-run ./...

  watchv:
    cmds:
      - ginkgo watch -v -r -p ./...

  watchvc:
    cmds:
      - ginkgo watch -v -r -p ./collections

  watchvi:
    cmds:
      - ginkgo watch -v -r -p ./i18n

  watchvn:
    cmds:
      - ginkgo watch -v -r -p ./nav

  watchvu:
    cmds:
      - ginkgo watch -v -r -p ./xfs/utils

  watch:
    cmds:
      - ginkgo watch -r -p ./...

  # initialise a test suite for a package. (only 1 per package)
  boot:
    cmds:
      - ginkgo bootstrap

  # run tests suites recursive
  g:
    cmds:
      - ginkgo -r

  # invoke as task gen -- <item>
  gl:
    cmds:
      - ginkgo -r --label-filter={{.CLI_ARGS}}

  # run tests suites recursive with verbose
  gv:
    cmds:
      - ginkgo -r -v

  # generate a test file for the item provided (item_test.go)
  # invoke as task gen -- <item>
  gen:
    cmds:
      - ginkgo generate {{.CLI_ARGS}}

  lint:
    cmds:
      - golangci-lint run

  publish-cover:
    cmds:
      - goveralls -repotoken {{.COVERALLS_TOKEN}}

  cover:
    cmds:
      - ginkgo --json-report ./ginkgo.report  -coverpkg=./... -coverprofile=./coverage/coverage.out -r
